name: Publish

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  vulnerability-scan:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        framework: [ net6.0, net7.0, net8.0 ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: scan-vulnerabilities/${{ matrix.os }}/${{ matrix.framework }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dotnet SDKs
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Scan for Vulnerabilities
        shell: bash
        run: |
          dotnet nuget list source
          dotnet restore
          dotnet list package --vulnerable --include-transitive --framework ${{ matrix.framework }} | tee vulnerabilities.txt
          ! cat vulnerabilities.txt | grep -q "has the following vulnerable packages"

  build-samples:
    timeout-minutes: 5
    name: build-samples/${{ matrix.framework }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        framework: [ net8.0 ]
    services:
      esdb:
        image: ghcr.io/eventstore/eventstore:lts
        env:
          EVENTSTORE_INSECURE: true
          EVENTSTORE_MEM_DB: false
          EVENTSTORE_RUN_PROJECTIONS: all
          EVENTSTORE_START_STANDARD_PROJECTIONS: true
        ports:
          - 2113:2113
        options: --health-cmd "exit 0"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dotnet SDKs
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x
      - name: Compile
        shell: bash
        run: |
          dotnet build samples
      - name: Run
        shell: bash
        run: |
          find samples/ -type f -iname "*.csproj" -print0 | xargs -0L1 dotnet run --framework ${{ matrix.framework }} --project

  generate-certificates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate certificates
        run: |
          mkdir -p certs
          docker run --rm --user root --volume "$PWD/certs:/tmp" ghcr.io/eventstore/es-gencert-cli:1.3 create-ca -out /tmp/ca
          docker run --rm --user root --volume "$PWD/certs:/tmp" ghcr.io/eventstore/es-gencert-cli:1.3 create-node -ca-certificate /tmp/ca/ca.crt -ca-key /tmp/ca/ca.key -out /tmp/node -ip-addresses 127.0.0.1 -dns-names localhost
          docker run --rm --user root --volume "$PWD/certs:/tmp" ghcr.io/eventstore/es-gencert-cli:1.3 create-user -username admin -ca-certificate /tmp/ca/ca.crt -ca-key /tmp/ca/ca.key -out /tmp/user-admin
          docker run --rm --user root --volume "$PWD/certs:/tmp" ghcr.io/eventstore/es-gencert-cli:1.3 create-user -username invalid -ca-certificate /tmp/ca/ca.crt -ca-key /tmp/ca/ca.key -out /tmp/user-invalid

      - name: Set permissions on certificates
        run: |
          sudo chown -R $USER:$USER certs
          sudo chmod -R 755 certs

      - name: Upload certificates
        uses: actions/upload-artifact@v2
        with:
          name: certs
          path: certs

  test:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        framework: [ net6.0, net7.0, net8.0 ]
        os: [ ubuntu-latest, windows-latest ]
        configuration: [ release ]
    runs-on: ${{ matrix.os }}
    name: test/EventStore.Client/${{ matrix.os }}/${{ matrix.framework }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - shell: bash
        run: |
          git fetch --prune --unshallow
      - name: Install dotnet SDKs
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Compile
        shell: bash
        run: |
          dotnet build --configuration ${{ matrix.configuration }} --framework ${{ matrix.framework }} src/EventStore.Client
      - name: Run Tests
        shell: bash
        run: |
          dotnet test --configuration ${{ matrix.configuration }} --blame \
            --logger:"GitHubActions;report-warnings=false" --logger:"console;verbosity=normal" \
            --framework ${{ matrix.framework }} \
            test/EventStore.Client.Tests